### ISSUE TITLE
Support for tagless components?

### ISSUE THREAD

**Issue by FezVrasta** [kybishop/ember-popper#3]
I think it would be a nice addition to support tagless components:
```
export default Ember.Component.extend({
  tagName: '',
});
```

**Comment by kybishop** [comment]
This must have been added right before I clicked the "Watch" button for the repo, sorry for the late response!

@FezVrasta do you mean targeting a tagless component, passing a tagless component into an `{{#ember-popper}}`, or something else?

**Comment by kybishop** [comment]
@FezVrasta just wanted to send a ping to hear your thoughts

**Comment by FezVrasta** [comment]
Sorry, I simply forwarded a request I got on my repository. I don't use Ember so I can't be much of a help...

**Comment by kybishop** [comment]
heh no worries.

I think our hands are a bit tied with _targeting_ tagless components, since popper.js needs an element to target.

One can currently pass _in_ a tagless component as the popper's content, though it will be automatically wrapped to give popper.js something to target.

Going to close this out for now, though happy to hear specific requests from people if there is a pattern they'd like to see enabled.
