### ISSUE TITLE
Decorators import scoped to `@ember`

### ISSUE THREAD

**Issue by snewcomer** [kybishop/ember-popper#81]
I am trying to figure out how to use `@ember-decorators` in a project consuming this addon.  Because the import is still `import { tagName } from 'ember-decorators/components`, I am getting a build error because in my project, I am importing it like so: `import { tagName } from '@ember-decorators/components` (2.0.0-beta.1).  Is there any way to resolve this other than forking and updating this addon to use the beta version of `ember-decorators`?

**Comment by kybishop** [comment]
I'm attempted to use the ember-decorators beta in #80, but ran into a bug with ember 3.1. @pzuraq how would you feel about me removing ember-decorators for now so people can still use ember-popper until we can get around to a fix in ember-decorators?

**Comment by pzuraq** [comment]
It would be a pretty big overhaul to remove decorators, if you'd rather drop them and classes for stability no problem, but it's not likely to be as simple as pop them out then back in. I can try to take a look at #80 tomorrow

**Comment by buschtoens** [comment]
https://github.com/kybishop/ember-attacher/issues/114#issuecomment-370095854

> I believe this issue is actually from ember-decorators, which don't have full ember 3.0 support yet, and ember-decorators is used in the positioning library, ember-popper.

Is that correct? I haven't yet discovered any problems with the v1 line of ember-decorators in my 3.0 app, but it might just be me.

If so, we either need to

- rip out ember-decorators
- upgrade to ember-decorators v2 beta

The latter would require users to upgrade their apps to v2 as well, which they probably should do anyway, because of the incompatibility with Ember 3. So basically users would have to install `0.8.3` and below for Ember 2 and `0.9.0` and above for Ember 3.

I would be happy to pitch a PR upgrading ember-popper to ember-decorators v2. Because right now, my app is broken :/

**Comment by pzuraq** [comment]
#80 does this, we just haven't had time to dig into why tests are failing

**Comment by buschtoens** [comment]
Oh yes, silly me. I'll try to look through it later. Maybe I find out something.

**Comment by kybishop** [comment]
This will be fixed once https://github.com/ember-decorators/argument/pull/62 lands

**Comment by kybishop** [comment]
This should be fixed by #80
